Description of testNonlinearOptimization
testNonlinearOptimization
PURPOSE
testNonlinearOptimization
SYNOPSIS
function testNonlinearOptimization
DESCRIPTION
 testNonlinearOptimization
 The script applyes nonlinear optimization to a Graph SLAM problem
 The test can be applied to any of the datasets in the ./Data folder
 '10K', '10KHOGMan','intel','Killian', 'VP'
 The user can choose to either incrementaly optimize the graph or to
 optimize the whole graph at once(batch)
 Author: Viorela Ila
CROSS-REFERENCE INFORMATION
This function calls:
addFactor [Config, System, Graph]=addFactor(factorR,Config, System, Graph)
initialConfiguration
nonlinearOptimization [Config,System]=nonlinearOptimization(Config,System,Graph,Solver,Plot)
cut2maxID cuts the graph to maxID and add some new set of indexes
loadDataSet [vertices,edges, dataFile]=loadDataSet(dataSet,saveFile)
PlotConfig PlotConfig(varargin)
This function is called by:
SOURCE CODE
function testNonlinearOptimization
% testNonlinearOptimization
% The script applyes nonlinear optimization to a Graph SLAM problem
% The test can be applied to any of the datasets in the ./Data folder
% '10K', '10KHOGMan','intel','Killian', 'VP'
% The user can choose to either incrementaly optimize the graph or to
% optimize the whole graph at once(batch)
% Author: Viorela Ila
close all;
clear all;
dataSet='intel';
saveFile=1; % save edges and vertices to a .mat file to speed up the reading when used again.
maxID=0; % steps to process, if '0', the whole data is processed
incremental=0;
[vertices,edges]=loadDataSet(dataSet,saveFile);
[Data.vert, Data.ed]=cut2maxID(maxID, vertices, edges);
Data.nVert=size(Data.vert,1);
Data.nEd=size(Data.ed,1);
Data.name=dataSet;
% PARAMETERS
%Solver
Solver.maxIT=200;
Solver.tol=1e-4;
Solver.linearSolver='spqr';
Solver.nonlinearSolver='GaussNewton';
Solver.lambda=10;
%Plot
%flags
Plot.InitConfig=0;
Plot.Config=1;
Plot.Error=0;
Plot.DMV=0;
Plot.spyMat=0;
Plot.measurement=1;
%params
Plot.faxis='off';
Plot.colour=[0.5,0.5,0.5];
Plot.ftitle=Data.name;
Plot.fname=sprintf('%s_',Data.name);
%CONFIG
Config.p0 = Data.vert(1,2:end)'; % prior
Config.s0 = diag([Data.ed(1,6),Data.ed(1,8),Data.ed(1,9)]); % noise on prior
Config.LandDim=2;   % landmark size
Config.PoseDim=3;   % pose size
Config.ndx=0;       % config index
Config.nPoses=0;    % number of poses
Config.nLands=0;    % number of landmarks
Config.id2config=zeros(Data.nVert,2); % variable id to position in the config vector converter
Config.id2config(Data.vert(1,1)+1,:)=[Config.nPoses,Config.nLands];
Config.vector=[Config.p0,[1,1,1]']; % the second column is used for rapid identification of the landmark=0 vs pose=1
Config.size=size(Config.vector,1);
%SYSTEM
System.ndx=1:Config.PoseDim;
R0=chol(inv(Config.s0));
System.A(System.ndx,System.ndx)=sparse(R0); % Given noise in the 1st pose
System.b(System.ndx,1)=zeros(Config.PoseDim,1); % the pose will not be updated
% GRAPH
% factors
Graph.F=[]; % keeps the factors
%variables
Graph.idX=Data.vert(1,1); % the id in the variables in the graph
if ~incremental
    % Build the system and initial configuration
    [Config, System, Graph]=initialConfiguration(Data,Config,System,Graph);
    % plot initial config
    if Plot.InitConfig
        PlotConfig(Plot,Config,Graph,'g','y');
    end
    % OPTIMIZE
    [Config, System]=nonlinearOptimization(Config,System,Graph,Solver,Plot);
else
    ind=1;
    while ind<=Data.nEd
        factorR=Data.ed(ind,:);
        [Config, System, Graph]=addFactor(factorR,Config, System, Graph);
        [Config, System]=nonlinearOptimization(Config,System,Graph,Solver,Plot);
        ind=ind+1;
    end
end
% plot final config and errors
PlotConfig(Plot,Config,Graph,'r','b');
if Plot.DMV
    figure
    plot(Config.dmv)
    title('DMV');
end
if Plot.Error
    figure
    plot(Config.all_error)
    title('Error');
end