Description of GaussNewtonOptimization
GaussNewtonOptimization
PURPOSE
[Config,System]=GaussNewtonOptimization(Config,System,Graph,Solver,Plot)
SYNOPSIS
function [Config,System]=GaussNewtonOptimization(Config,System,Graph,Solver,Plot)
DESCRIPTION
 [Config,System]=GaussNewtonOptimization(Config,System,Graph,Solver,Plot)
 The script applyes Gauss-Newton nonlinear optimization to a Graph SLAM problem
 Returns a new configuraton: Config and the relinearized system: System
 Author: Viorela Ila
CROSS-REFERENCE INFORMATION
This function calls:
newConfig2D
linearSystem System=linearSystem(Config,Graph,System)
This function is called by:
nonlinearOptimization [Config,System]=nonlinearOptimization(Config,System,Graph,Solver,Plot)
SOURCE CODE
function [Config,System]=GaussNewtonOptimization(Config,System,Graph,Solver,Plot)
% [Config,System]=GaussNewtonOptimization(Config,System,Graph,Solver,Plot)
% The script applyes Gauss-Newton nonlinear optimization to a Graph SLAM problem
% Returns a new configuraton: Config and the relinearized system: System
% Author: Viorela Ila
i=1;
if Plot.Error,Config.dmv=zeros(1,Solver.maxIT); end;
if Plot.DMV,Config.dmv=zeros(1,Solver.maxIT); end;
if Plot.Config, Config.all=zeros(Config.size,Solver.maxIT); end;
done=(i>=Solver.maxIT);
disp('Optimize...');
while ~done
    %dm=spqr_solve(A,b);
    dm=spqr_solve(System.A,System.b,struct('ordering','colamd'));
    %plots
    if Plot.DMV, Config.dmv(i)=norm(dm); end;
    if Plot.Error, Config.all_error(i)=norm(System.A*dm-System.b); end;%/norm(b); end;
    if Plot.Config, Config.all(:,i)=Config.vector(:,1); end;
    done=((norm(dm)<Solver.tol)||(i>=Solver.maxIT));
    if ~done
        Config=newConfig2D(Config,dm);
        System=linearSystem(Config,Graph,System);
        i=i+1;
    end
    fprintf('.');
    if mod(i,50)==0
        fprintf('\n');
    end
end
if Plot.Error,Config.all_error=Config.all_error(1:i);
else Config.all_error(i)=norm(System.A*dm-System.b);%/norm(b);
end;
if Plot.DMV,Config.dmv=Config.dmv(1:i);
else Config.dmv(i)=norm(dm);
end;
if Plot.Config, Config.all=Config.all(:,1:i);
else Config.all=Config.vector(:,1);
end;
fprintf('\n');