Description of nonlinearOptimization
nonlinearOptimization
PURPOSE
[Config,System]=nonlinearOptimization(Config,System,Graph,Solver,Plot)
SYNOPSIS
function [Config, System]=nonlinearOptimization(Config,System,Graph,Solver,Plot)
DESCRIPTION
 [Config,System]=nonlinearOptimization(Config,System,Graph,Solver,Plot)
 The script selects the nonlinear optimization method
 Returns a new configuraton: Config and the relinearized system: System
 Author: Viorela Ila
CROSS-REFERENCE INFORMATION
This function calls:
GaussNewtonOptimization [Config,System]=GaussNewtonOptimization(Config,System,Graph,Solver,Plot)
LevenbergMarquardtOptimization [Config,System]=LevenbergMarquardtOptimization(Config,System,Graph,Solver,Plot)
This function is called by:
testNonlinearOptimization testNonlinearOptimization
SOURCE CODE
function [Config, System]=nonlinearOptimization(Config,System,Graph,Solver,Plot)
% [Config,System]=nonlinearOptimization(Config,System,Graph,Solver,Plot)
% The script selects the nonlinear optimization method
% Returns a new configuraton: Config and the relinearized system: System
% Author: Viorela Ila
switch Solver.nonlinearSolver
    case 'GaussNewton'
        [Config, System]=GaussNewtonOptimization(Config,System,Graph,Solver,Plot);
    case 'LevenbergMarquardt'
        [Config,System]=LevenbergMarquardtOptimization(Config,System,Graph,Solver,Plot);
    otherwise
        error('This method is not implemented');
end