Description of addFactorPose
addFactorPose
PURPOSE
Config=addPose(factorR,Config)
SYNOPSIS
function System=addFactorPose(factorR,Config,System)
DESCRIPTION
 Config=addPose(factorR,Config)
 The script adds a new pose factor to the current System
 Author: Viorela Ila
CROSS-REFERENCE INFORMATION
This function calls:
InvertEdge
pi2pi Moves an angle to the -pi,pi range.
Absolute2Relative computes the relative position of p2 in coordinates of p1.
Absolute2RelativeJacobian Jacobian of the relative displacement between two poses.
This function is called by:
addFactor [Config, System, Graph]=addFactor(factorR,Config, System, Graph)
linearSystem System=linearSystem(Config,Graph,System)
SOURCE CODE
function System=addFactorPose(factorR,Config,System)
% Config=addPose(factorR,Config)
% The script adds a new pose factor to the current System
% Author: Viorela Ila
Sz=diag([1/factorR(6);1/factorR(8);1/factorR(9)]); % only diag cov.
R=chol(inv(Sz)); %S^(-1/2)
% The 2 poses linked by the constraint
s1=factorR(2);
s2=factorR(1);
% % check for the order of ids and invert the transformation if needed
if (s1>s2)
    z=factorR(3:5)';
    s1=factorR(1);
    s2=factorR(2);
else
     z=InvertEdge(factorR(3:5)');
end
ndx1=[Config.PoseDim*Config.id2config((s1+1),1)+Config.LandDim*Config.id2config((s1+1),2)]+[1:Config.PoseDim];
ndx2=[Config.PoseDim*Config.id2config((s2+1),1)+Config.LandDim*Config.id2config((s2+1),2)]+[1:Config.PoseDim];
p1=Config.vector(ndx1,1); % The estimation of the two poses
p2=Config.vector(ndx2,1);
h=Absolute2Relative(p1,p2); % Estimation
[H1 H2]=Absolute2RelativeJacobian(p1,p2); % Jacobian
% Update System
System.ndx=System.ndx(end)+1:System.ndx(end)+Config.PoseDim;
System.A(System.ndx,ndx1)=sparse2(R*H1); % Jacobian matrix
System.A(System.ndx,ndx2)=sparse2(R*H2);
d=z-h;
d(end)=pi2pi(d(end));
System.b(System.ndx)=R*d; % Independent term