Description of addFactorLandmark
addFactorLandmark
PURPOSE
Config=addPose(factorR,Config)
SYNOPSIS
function System=addFactorLandmark(factorR,Config,System)
DESCRIPTION
 Config=addPose(factorR,Config)
 The script adds a new landmark factor to the current System
 Author: Viorela Ila
CROSS-REFERENCE INFORMATION
This function calls:
pi2pi Moves an angle to the -pi,pi range.
AbsolutePoint2RBObs Relative observation of a point from a pose.
AbsolutePoint2RBObsJacobian Jacobian of the relative range-and-bearing from a pose to a point.
This function is called by:
addFactor [Config, System, Graph]=addFactor(factorR,Config, System, Graph)
linearSystem System=linearSystem(Config,Graph,System)
SOURCE CODE
function System=addFactorLandmark(factorR,Config,System)
% Config=addPose(factorR,Config)
% The script adds a new landmark factor to the current System
% Author: Viorela Ila
Sz=diag([1/factorR(6);1/factorR(8)]); % only diag cov.
R=chol(inv(Sz)); %S^(-1/2)
% The 2 poses linked by the constraint
s1=factorR(2); % robot
s2=factorR(1); % landmark
z=factorR(3:4)';
ndx1=[Config.PoseDim*Config.id2config((s1+1),1)+Config.LandDim*Config.id2config((s1+1),2)]+[1:Config.PoseDim];
ndx2=[Config.PoseDim*Config.id2config((s2+1),1)+Config.PoseDim+Config.LandDim*Config.id2config((s2+1),2)-Config.LandDim]+[1:Config.LandDim];
P1=Config.vector(ndx1); % The estimation of the two poses
pt=Config.vector(ndx2);
h=AbsolutePoint2RBObs(P1,pt); % Estimation
[H1 H2]=AbsolutePoint2RBObsJacobian(P1,pt);
% Update System
System.ndx=System.ndx(end)+1:System.ndx(end)+Config.LandDim;
System.A(System.ndx,ndx1)=sparse2(R*H1); % Jacobian matrix
System.A(System.ndx,ndx2)=sparse2(R*H2);
d=z-h;
d(end)=pi2pi(d(end));
System.b(System.ndx)=R*d; % Independent term