Description of linearSystem
linearSystem
PURPOSE
System=linearSystem(Config,Graph,System)
SYNOPSIS
function System=linearSystem(Config,Graph,System)
DESCRIPTION
 System=linearSystem(Config,Graph,System)
 The script linearizes the nonlinear system on the current linearization
 points given by Config
 Returns the relinearized system: System
 Author: Viorela Ila
CROSS-REFERENCE INFORMATION
This function calls:
addFactorLandmark Config=addPose(factorR,Config)
addFactorPose Config=addPose(factorR,Config)
This function is called by:
GaussNewtonOptimization [Config,System]=GaussNewtonOptimization(Config,System,Graph,Solver,Plot)
LevenbergMarquardtOptimization [Config,System]=LevenbergMarquardtOptimization(Config,System,Graph,Solver,Plot)
SOURCE CODE
function System=linearSystem(Config,Graph,System)
% System=linearSystem(Config,Graph,System)
% The script linearizes the nonlinear system on the current linearization
% points given by Config
% Returns the relinearized system: System
% Author: Viorela Ila
nObs=size(Graph.F,1);
R0=chol(inv(Config.s0));
System.ndx=1:Config.PoseDim;
%System.A=sparse(zeros(size(System.A))); %This is not needed!!!!
%System.b=zeros(size(System.b));
System.A(System.ndx,System.ndx)=sparse(R0); % Given noise in the 1st pose
System.b(System.ndx)=zeros(Config.PoseDim,1); % the pose will not be updated
for i=1:nObs
    factorR=Graph.F(i,:);
    if factorR(end)~=99999
        System=addFactorPose(factorR,Config,System);
    else
        System=addFactorLandmark(factorR,Config,System);
    end
end