Description of addFactor
addFactor
PURPOSE
[Config, System, Graph]=addFactor(factorR,Config, System, Graph)
SYNOPSIS
function [Config, System, Graph]=addFactor(factorR,Config, System, Graph)
DESCRIPTION
 [Config, System, Graph]=addFactor( factorR,Config, System, Graph)
 The script adds a new factor to the current representation:
 Config, System and Graph
 Author: Viorela Ila
CROSS-REFERENCE INFORMATION
This function calls:
InvertEdge
addLandmark Config=addPose(factorR,Config)
addPose Config=addPose(factorR,Config)
addFactorLandmark Config=addPose(factorR,Config)
addFactorPose Config=addPose(factorR,Config)
This function is called by:
initialConfiguration
testNonlinearOptimization testNonlinearOptimization
SOURCE CODE
function [Config, System, Graph]=addFactor(factorR,Config, System, Graph)
% [Config, System, Graph]=addFactor(factorR,Config, System, Graph)
% The script adds a new factor to the current representation:
% Config, System and Graph
% Author: Viorela Ila
if factorR(end)~=99999
     if factorR(2)>factorR(1)
         % in this case we need to invert the edge
         factorR(1:2)=factorR(2:-1:1);
         factorR(3:5)=InvertEdge(factorR(3:5)')';
     end
    if (ismember(factorR(2),Graph.idX))
        if(ismember(factorR(1),Graph.idX))
           factorType='poseConstr';
        else
            factorType='odometric';
        end
    else
        error('Disconnected graph!!')
        return;
    end
else
    if(ismember(factorR(1),Graph.idX))
        factorType='landmark';
    else
        factorType='new_landmark';
    end
end
switch factorType
    case 'odometric'
        Config=addPose(factorR,Config);
        System=addFactorPose(factorR,Config,System);
        Graph.idX= [Graph.idX;factorR(1)];
        Graph.F=[Graph.F;factorR];
    case 'poseConstr'
        System=addFactorPose(factorR,Config,System);
        Graph.F=[Graph.F;factorR];
    case 'new_landmark'
        Config=addLandmark(factorR,Config);
        System=addFactorLandmark(factorR,Config,System);
        Graph.idX= [Graph.idX;factorR(1)];
        Graph.F=[Graph.F;factorR];
    case 'landmark'
        System=addFactorLandmark(factorR,Config,System);
        Graph.F=[Graph.F;factorR];
end