Description of addPose
addPose
PURPOSE
Config=addPose(factorR,Config)
SYNOPSIS
function Config=addPose(factorR,Config)
DESCRIPTION
 Config=addPose(factorR,Config)
 The script adds a new pose to the current Config
 Author: Viorela Ila
CROSS-REFERENCE INFORMATION
This function calls:
InvertEdge
Relative2Absolute computes the absolute position of p2 knowing p1 and d. p1 and d must be
This function is called by:
addFactor [Config, System, Graph]=addFactor(factorR,Config, System, Graph)
SOURCE CODE
function Config=addPose(factorR,Config)
% Config=addPose(factorR,Config)
% The script adds a new pose to the current Config
% Author: Viorela Ila
s1=factorR(2); % pose in the config
s2=factorR(1); % new pose
odo=factorR(3:5);
ndx1=[Config.PoseDim*Config.id2config((s1+1),1)+Config.LandDim*Config.id2config((s1+1),2)]+[1:Config.PoseDim]; %Change this formula
p1=Config.vector(ndx1,1);
d=InvertEdge(odo');
p2=Relative2Absolute(p1,d);
% update Config
Config.vector=[Config.vector;[p2,[1,1,1]']];
Config.size=size(Config.vector,1);
Config.ndx=Config.ndx+1;
Config.nPoses=Config.nPoses+1;
Config.id2config((s2+1),:)=[Config.nPoses,Config.nLands];