Description of InvertEdge
InvertEdge
PURPOSE
SYNOPSIS
function ie=InvertEdge(e)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
Absolute2Relative computes the relative position of p2 in coordinates of p1.
This function is called by:
addFactor [Config, System, Graph]=addFactor(factorR,Config, System, Graph)
addPose Config=addPose(factorR,Config)
addFactorPose Config=addPose(factorR,Config)
SOURCE CODE
function ie=InvertEdge(e)
  ie=Absolute2Relative(e,[0;0;0]);