Description of newConfig2D
newConfig2D
PURPOSE
SYNOPSIS
function [Config]=newConfig2D(Config,dm)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
pi2pi Moves an angle to the -pi,pi range.
This function is called by:
GaussNewtonOptimization [Config,System]=GaussNewtonOptimization(Config,System,Graph,Solver,Plot)
LevenbergMarquardtOptimization [Config,System]=LevenbergMarquardtOptimization(Config,System,Graph,Solver,Plot)
SOURCE CODE
function [Config]=newConfig2D(Config,dm)
Config.vector(:,1)=Config.vector(:,1)+dm;
ndx=1:Config.PoseDim;
while ndx < Config.size
    if size(ndx,2)==Config.PoseDim
        Config.vector(ndx(end))=pi2pi(Config.vector(ndx(end)));
    end
    if Config.vector(ndx(end)+1,2)~=0
        ndx=ndx+Config.PoseDim;
    else
        ndx=ndx(end-Config.LandDim+1:end)+Config.LandDim;
    end
end