Description of pi2pi
pi2pi
PURPOSE
Moves an angle to the -pi,pi range.
SYNOPSIS
function angle=pi2pi(angle)
DESCRIPTION
 Moves an angle to the -pi,pi range.
 Ensures that the given angles are all in the -pi, pi range.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
newConfig2D
Absolute2Relative computes the relative position of p2 in coordinates of p1.
AbsolutePoint2RBObs Relative observation of a point from a pose.
Relative2Absolute computes the absolute position of p2 knowing p1 and d. p1 and d must be
addFactorLandmark Config=addPose(factorR,Config)
addFactorPose Config=addPose(factorR,Config)
SOURCE CODE
% Moves an angle to the -pi,pi range.
%
% Ensures that the given angles are all in the -pi, pi range.
function angle=pi2pi(angle)
  dp=2*pi;
  ang=(angle<=-dp)||(angle>=dp);
  angle(ang)=mod(angle(ang),dp);
  ang=angle>=pi;
    angle(ang)=angle(ang)-2*pi;
    ang=angle<=-pi;
    angle(ang)=angle(ang)+2*pi;